#!/usr/bin/env python3
# Generated by scripts/check.sh from backend/api-documentation-master/scripts/; edit the canonical file.
"""Validate local OpenAPI documents. Exit 0 valid, 1 invalid, 2 not verified.

Dependencies: requirements.txt beside this script. References may resolve only to
files within the input document's directory; remote retrieval is never performed.
This validates the OpenAPI schema, not live API behavior or authorization.
"""
import argparse
import json
import os
from pathlib import Path
from urllib.parse import unquote, urlparse

SKIP = {'.git', 'node_modules', '.venv', 'venv', 'dist', 'build', '__pycache__'}


def find_api_files(target):
    target = Path(target)
    if target.is_file():
        return [target]
    found = set()
    for root, dirs, files in os.walk(target):
        dirs[:] = [name for name in dirs if name not in SKIP]
        for name in files:
            path = Path(root) / name
            if path.suffix.lower() in {'.json', '.yaml', '.yml'} and ('openapi' in name.lower() or 'swagger' in name.lower()):
                found.add(path)
    return sorted(found)


def check_openapi_spec(file_path):
    path = Path(file_path).resolve()
    result = {'file': str(path), 'type': 'openapi', 'status': 'unverified', 'passed': [], 'issues': []}
    try:
        import yaml
        from jsonschema_path import SchemaPath
        from openapi_spec_validator.shortcuts import get_validator_cls
    except ImportError as error:
        result['issues'].append(f'Missing validator dependency: {error.name}; install scripts/requirements.txt')
        return result

    class LocalOnlyError(ValueError):
        pass

    def load_local(uri):
        parsed = urlparse(uri)
        if parsed.scheme != 'file' or parsed.netloc not in {'', 'localhost'}:
            raise LocalOnlyError('Remote references are not supported; bundle them locally first')
        referenced = Path(unquote(parsed.path)).resolve()
        if not referenced.is_relative_to(path.parent):
            raise LocalOnlyError('Reference leaves the input document directory; bundle it locally first')
        return yaml.safe_load(referenced.read_text(encoding='utf-8'))

    try:
        spec = yaml.safe_load(path.read_text(encoding='utf-8')) if path.suffix.lower() != '.json' else json.loads(path.read_text(encoding='utf-8'))
        if not isinstance(spec, dict):
            raise ValueError('OpenAPI document must be an object')
        # Override every retrieval handler, including the fallback: no network or
        # arbitrary filesystem reads can occur through a nested $ref or $id.
        schema = SchemaPath.from_dict(spec, base_uri=path.as_uri(), handlers={key: load_local for key in ('file', 'http', 'https', '<all_urls>')})
        get_validator_cls(spec)(schema).validate()
    except Exception as error:
        # The resolver wraps retrieval exceptions. Preserve unsupported coverage as
        # unverified while schema/parsing/unresolved local reference errors fail.
        chain, current = [], error
        while current is not None and id(current) not in {id(item) for item in chain}:
            chain.append(current)
            current = current.__cause__ or current.__context__
        result['status'] = 'unverified' if any(isinstance(item, LocalOnlyError) for item in chain) else 'invalid'
        result['issues'].append(str(error))
        return result
    result['status'] = 'valid'
    result['passed'].append('OpenAPI schema and supported local references validated')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('target', nargs='?', default='.', help='A specification file, or a directory to discover OpenAPI/Swagger filenames')
    args = parser.parse_args()
    target = Path(args.target)
    files = find_api_files(target) if target.exists() else []
    results = [check_openapi_spec(path) for path in files]
    status = 'unverified' if not results or any(r['status'] == 'unverified' for r in results) else 'invalid' if any(r['status'] == 'invalid' for r in results) else 'valid'
    report = {'status': status, 'checked_files': len(results), 'results': results}
    if not files:
        report['message'] = 'No specification found; supply its path explicitly. No API behavior was checked.'
    print(json.dumps(report, indent=2))
    return {'valid': 0, 'invalid': 1, 'unverified': 2}[status]


if __name__ == '__main__':
    raise SystemExit(main())
