#!/usr/bin/env python3
"""Validate the catalogue; refresh generated copies/links unless --check is set."""
import argparse
import json
import re
from pathlib import Path
from urllib.parse import unquote

CATEGORIES = ('backend', 'engineering', 'frontend', 'infra', 'productivity', 'quality', 'security', 'workflow', 'writing')
GENERATED = '# Generated by scripts/check.sh from backend/api-documentation-master/scripts/; edit the canonical file.\n'


def markdown_links(text):
    fence = None
    for line in text.splitlines():
        match = re.match(r'^\s*(`{3,}|~{3,})', line)
        if match:
            marker = match.group(1)[0]
            fence = None if fence == marker else marker if fence is None else fence
            continue
        if fence:
            continue
        for target in re.findall(r'\[[^\]]*\]\(([^)]+)\)', line):
            yield target.strip().strip('<>')
        match = re.match(r'^\s*\[[^\]]+\]:\s*(\S+)', line)
        if match:
            yield match.group(1).strip('<>')


def validate(root, check_only=False):
    problems = []
    entries = [entry for category in CATEGORIES for entry in sorted((root / category).glob('*/SKILL.md'))]
    names = {}
    for entry in entries:
        content = entry.read_text()
        match = re.match(r'^---\n(.*?)\n---\n', content, re.S)
        if not match:
            problems.append(f'{entry.relative_to(root)}: missing frontmatter')
            continue
        fm = match.group(1)
        fields = dict(re.findall(r'^(name|description):\s*(.+)$', fm, re.M))
        name = fields.get('name', '').strip('"\'')
        description = fields.get('description', '').strip('"\'')
        if name != entry.parent.name or not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', name):
            problems.append(f'{entry.relative_to(root)}: invalid/mismatched name')
        if not description or len(description) > 1024:
            problems.append(f'{entry.relative_to(root)}: empty or excessive description')
        if name in names:
            problems.append(f'{name}: duplicate entrypoint')
        names[name] = entry
        readme = entry.parent.parent / 'README.md'
        if not readme.exists() or f']({name}/SKILL.md)' not in readme.read_text():
            problems.append(f'{name}: missing category README entry')
        if re.search(r'^disable-model-invocation:\s*true\s*$', fm, re.M):
            policy = entry.parent / 'agents/openai.yaml'
            if not policy.exists() or not re.search(r'^  allow_implicit_invocation: false\s*$', policy.read_text(), re.M):
                problems.append(f'{name}: manual invocation missing Codex policy')
    for filename in ('api_validator.py', 'requirements.txt'):
        source = root / 'backend/api-documentation-master/scripts' / filename
        destination = root / 'backend/api-patterns/scripts' / filename
        original = source.read_text()
        expected = original.split('\n', 1)[0] + '\n' + GENERATED + original.split('\n', 1)[1] if filename.endswith('.py') else GENERATED + original
        if not destination.exists() or destination.read_text() != expected:
            if check_only:
                problems.append(f'{destination.relative_to(root)}: generated validator copy drifted')
            else:
                destination.write_text(expected)
    docs = [root / 'README.md', root / 'MIGRATION.md']
    docs += [root / category / 'README.md' for category in CATEGORIES]
    for entry in entries:
        docs.extend(path for path in entry.parent.rglob('*.md') if not any(part in {'node_modules', '__pycache__'} for part in path.relative_to(entry.parent).parts))
    for doc in docs:
        if not doc.exists():
            problems.append(f'{doc.relative_to(root)}: missing document')
            continue
        for raw in markdown_links(doc.read_text()):
            target = raw.split('#', 1)[0]
            if not target or re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', target):
                continue
            # Markdown link titles are distinct from filenames. Angle-bracket paths
            # with spaces remain supported; examples belong in fenced code blocks.
            target = re.sub(r'\s+["\'].*["\']$', '', target).strip('<>')
            resolved = doc.parent / unquote(target)
            if not resolved.exists():
                problems.append(f'{doc.relative_to(root)}: dead link {raw}')
    if 'ui-ux-pro-max' in names:
        provenance = root / 'frontend/ui-ux-pro-max/data/upstream.json'
        if not provenance.is_file():
            problems.append('ui-ux-pro-max: missing data provenance')
        else:
            for item in json.loads(provenance.read_text())['files']:
                if not (provenance.parent / item['path']).is_file():
                    problems.append(f"ui-ux-pro-max: missing catalogue data {item['path']}")
    retired = json.loads((root / 'scripts/retired-skills.json').read_text())
    for source, destination in retired.items():
        if (root / source / 'SKILL.md').exists():
            problems.append(f'{source}: retired entrypoint still active')
        if destination and not (root / destination / 'SKILL.md').exists():
            problems.append(f'{source}: merger target missing')
    bundle = root / 'skills'
    if bundle.is_symlink() or (bundle.exists() and not bundle.is_dir()):
        problems.append('skills/: expected a real generated directory')
    else:
        if not check_only:
            bundle.mkdir(exist_ok=True)
        for path in bundle.iterdir() if bundle.exists() else []:
            if path.name not in names:
                if not check_only and path.is_symlink():
                    path.unlink()
                else:
                    problems.append(f'skills/{path.name}: unexpected entry (real files are never removed)')
        for name, entry in names.items():
            target = Path('..') / entry.parent.relative_to(root)
            link = bundle / name
            if link.is_symlink() and link.readlink() == target:
                continue
            if check_only:
                problems.append(f'skills/{name}: missing or drifted plugin link')
            elif link.exists() and not link.is_symlink():
                problems.append(f'skills/{name}: real files preserved; cannot replace with generated link')
            else:
                if link.is_symlink():
                    link.unlink()
                link.symlink_to(target)
    return entries, problems


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    entries, problems = validate(Path(__file__).resolve().parent.parent, args.check)
    if problems:
        print('\n'.join(problems))
        print(f'{len(problems)} problem(s)')
        return 1
    print(f'{len(entries)} skills: catalogue, local links, invocation policies and generated files valid')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
